# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e9f617151678a6e7d7a4eac7836e82b9c57855e5c988b602330ebeec5e29f23b1c5bd67ef1f3cd93b66acd4da1af9b48d228a4696e341b73707e5d161def4c

test:
  secret_key_base: bfe31c8180bf0482eec7f4a34afef8b9fd03bbd2567e3f1cf54fe52718e6bb47e87268d39e42efbd3876e166c01f94d55c8ae8d386fe892816fe6766f5eb3b19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
